version: '3'

services:

#  app_backend:
#    container_name: "app_backend"
#    environment:
#      - FLASK_APP=${FLASK_APP}
#      - FLASK_DEBUG=${FLASK_DEBUG}
#      - SECRET_KEY=${SECRET_KEY}
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_PORT=${POSTGRES_PORT}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=${POSTGRES_DB}
#    image: app_backend
#    build:
#      context: backend/
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    depends_on:
#      - app_db
#    links:
#      - app_db

  app_db:
    image: postgres:10.12
    container_name: app_db
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
